version = "3.7.4"

runner.dialect = scala3

maxColumn = 100
align.openParenCallSite = false
align.openParenDefnSite = false

danglingParentheses.preset = true

indent.main = 2
indent.callSite = 2
indent.defnSite = 2

spaces.inImportCurlyBraces = true
spaces.inByNameTypes = true
spaces.afterKeywordBeforeParen = true

binPack.unsafeCallSite = false
binPack.unsafeDefnSite = false

optIn.breakChainOnFirstMethodDot = true
optIn.configStyleArguments = true
