curl -X POST http://localhost:9000/mcp/resources/call \
  -H "Content-Type: application/json" \
  -d '{
    "name": "getMovies",
    "params": {}
  }

curl -X POST http://localhost:9000/mcp/tools/call \
  -H "Content-Type: application/json" \
  -d '{
    "name": "bookmark",
    "params": { "movie": "Inception" }
  }'
