# https://www.playframework.com/documentation/latest/Configuration
play.filters.enabled += "play.filters.cors.CORSFilter"

play.filters.cors {
  allowedOrigins = ["http://localhost:6274"]
  allowedHttpMethods = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
  allowedHttpHeaders = ["Accept", "Content-Type", "Origin", "Authorization", "X-Requested-With", "MCP-Protocol-Version"]
  exposedHeaders = ["Location", "Link"]
  supportsCredentials = true
  preflightMaxAge = 3600
}
